### ISSUE TITLE
Critical error in the application

### ISSUE THREAD

**Issue by MuratovAS** [jacen92/fdroid-docker-server#5]
Good afternoon.
I tried to run your application and got this error. 

~~~bash
docker run --rm -p 80:80 -p 22:22 -v $PWD/config:/opt/config --name fdroid fdroid
~~~

~~~
Update fdroid scp password
No custom authorized_keys file found in /opt/config
No custom config.py file found
No custom config.in.py file found in /opt/config
No custom keystore.jks file found in /opt/config
Copy apks from /opt/apk
Run fdroid update
INFO: Creating signed index with this key (SHA256):..............................
INFO: Creating signed index with this key (SHA256):..............................
INFO: Finished
INFO: Creating signed index with this key (SHA256):..............................
INFO: Creating signed index with this key (SHA256):..............................
INFO: Finished
/
Starting nginx and ssh daemons
Monitoring /home/fdroid directory
Setting up watches.
Watches established.
The file 'F-Droid.apk' appeared in directory '/home/fdroid/' via 'CLOSE_WRITE,CLOSE'
CRITICAL: Unknown exception found!
Traceback (most recent call last):
  File "/usr/bin/fdroid", line 170, in <module>
    main()
  File "/usr/bin/fdroid", line 165, in main
    raise e
  File "/usr/bin/fdroid", line 146, in main
    mod.main()
  File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1968, in main
    apks, cachechanged = process_apks(apkcache, repodirs[0], knownapks, options.use_date_from_apk)
  File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1496, in process_apks
    use_date_from_apk, ada, True)
  File "/usr/lib/python3/dist-packages/fdroidserver/update.py", line 1410, in process_apk
    if not common.verify_apk_signature(apkfile):
  File "/usr/lib/python3/dist-packages/fdroidserver/common.py", line 2867, in verify_apk_signature
    output = subprocess.check_output(args + [apk])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/usr/bin/apksigner'
Backup to persistant volume
~~~

**Comment by jacen92** [comment]
Hello,

OSError: [Errno 8] Exec format error: '/usr/bin/apksigner'
This tihing suggest that you run the container on an other architecture. Like you built on x86 and run on arm..

On an other track it is possible that fdroid change something in the past months.

On which platform do you use the image?
Do you built it from scratch?

**Comment by MuratovAS** [comment]
I did everything according to the instructions from the master branch.
Run `docker build --rm -t fdroid -f Dockerfile .`, added  `auth.txt`.
All operations were performed on intel x64_86
